import { mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { format } from 'date-fns';
import type { AnalyzedTweet, Digest } from '../types.js';
import { OUTPUT_DIR } from '../config.js';

export function generateMarkdownReport(
  date: string,
  language: 'en' | 'zh',
  tweets: AnalyzedTweet[]
): string {
  const lines: string[] = [];

  // Header
  lines.push(`# Social Radar - Twitter Analysis - ${date}`);
  lines.push('');

  // Summary
  const sheinRelated = tweets.filter((t) => t.sheinRelevance.isRelevant);
  const sentiment = {
    positive: tweets.filter((t) => t.sentiment.sentiment === 'positive').length,
    negative: tweets.filter((t) => t.sentiment.sentiment === 'negative').length,
    neutral: tweets.filter((t) => t.sentiment.sentiment === 'neutral').length,
  };

  lines.push(language === 'en' ? '## 📊 Summary' : '## 📊 总览');
  lines.push('');
  lines.push(`- **${language === 'en' ? 'Total Tweets' : '总推文数'}**: ${tweets.length}`);
  lines.push(`- **${language === 'en' ? 'SHEIN Related' : 'SHEIN相关'}**: ${sheinRelated.length} (${((sheinRelated.length / tweets.length) * 100).toFixed(1)}%)`);
  lines.push('');
  lines.push(`### ${language === 'en' ? 'Sentiment Breakdown' : '情感分析'}`);
  lines.push(`- 😊 ${language === 'en' ? 'Positive' : '正面'}: ${sentiment.positive} (${((sentiment.positive / tweets.length) * 100).toFixed(1)}%)`);
  lines.push(`- 😐 ${language === 'en' ? 'Neutral' : '中性'}: ${sentiment.neutral} (${((sentiment.neutral / tweets.length) * 100).toFixed(1)}%)`);
  lines.push(`- 😞 ${language === 'en' ? 'Negative' : '负面'}: ${sentiment.negative} (${((sentiment.negative / tweets.length) * 100).toFixed(1)}%)`);
  lines.push('');

  // SHEIN Related Tweets
  if (sheinRelated.length > 0) {
    lines.push(language === 'en' ? '## 🎯 SHEIN Related Tweets' : '## 🎯 SHEIN相关推文');
    lines.push('');

    // Group by sentiment
    const positive = sheinRelated.filter((t) => t.sentiment.sentiment === 'positive');
    const negative = sheinRelated.filter((t) => t.sentiment.sentiment === 'negative');
    const neutral = sheinRelated.filter((t) => t.sentiment.sentiment === 'neutral');

    if (positive.length > 0) {
      lines.push(`### 😊 ${language === 'en' ? 'Positive' : '正面评价'} (${positive.length})`);
      lines.push('');
      for (const tweet of positive.slice(0, 10)) {
        lines.push(formatTweet(tweet, language));
        lines.push('');
      }
    }

    if (negative.length > 0) {
      lines.push(`### 😞 ${language === 'en' ? 'Negative' : '负面评价'} (${negative.length})`);
      lines.push('');
      for (const tweet of negative.slice(0, 10)) {
        lines.push(formatTweet(tweet, language));
        lines.push('');
      }
    }

    if (neutral.length > 0) {
      lines.push(`### 😐 ${language === 'en' ? 'Neutral' : '中性评论'} (${neutral.length})`);
      lines.push('');
      for (const tweet of neutral.slice(0, 10)) {
        lines.push(formatTweet(tweet, language));
        lines.push('');
      }
    }
  }

  // All Tweets by Account
  lines.push(language === 'en' ? '## 📱 All Tweets by Account' : '## 📱 按账号分类');
  lines.push('');

  const byAccount = groupByAccount(tweets);
  for (const [username, accountTweets] of Object.entries(byAccount)) {
    lines.push(`### @${username} (${accountTweets.length})`);
    lines.push('');
    for (const tweet of accountTweets.slice(0, 5)) {
      lines.push(formatTweet(tweet, language));
      lines.push('');
    }
  }

  // Footer
  lines.push('---');
  lines.push('');
  lines.push(`${language === 'en' ? 'Generated by' : '由'} Social Radar ${language === 'en' ? '' : '生成'} 🔭`);
  lines.push('');

  return lines.join('\n');
}

function formatTweet(tweet: AnalyzedTweet, language: 'en' | 'zh'): string {
  const lines: string[] = [];

  const sentimentEmoji = {
    positive: '😊',
    negative: '😞',
    neutral: '😐',
  }[tweet.sentiment.sentiment];

  lines.push(`#### ${sentimentEmoji} [@${tweet.authorUsername}](https://twitter.com/${tweet.authorUsername}/status/${tweet.id})`);
  lines.push('');
  lines.push(`> ${tweet.text.replace(/\n/g, '\n> ')}`);
  lines.push('');

  if (tweet.metrics) {
    lines.push(`💙 ${tweet.metrics.likeCount} | 🔁 ${tweet.metrics.retweetCount} | 💬 ${tweet.metrics.replyCount}`);
    lines.push('');
  }

  lines.push(`**${language === 'en' ? 'Sentiment' : '情感'}**: ${tweet.sentiment.summary}`);

  if (tweet.sheinRelevance.isRelevant) {
    lines.push(`**${language === 'en' ? 'SHEIN Relevance' : 'SHEIN相关性'}**: ${tweet.sheinRelevance.reason}`);
    if (tweet.sheinRelevance.keywords.length > 0) {
      lines.push(`**${language === 'en' ? 'Keywords' : '关键词'}**: ${tweet.sheinRelevance.keywords.join(', ')}`);
    }
  }

  lines.push(`**${language === 'en' ? 'Posted' : '发布时间'}**: ${new Date(tweet.createdAt).toLocaleString(language === 'en' ? 'en-US' : 'zh-CN')}`);

  return lines.join('\n');
}

function groupByAccount(tweets: AnalyzedTweet[]): Record<string, AnalyzedTweet[]> {
  const groups: Record<string, AnalyzedTweet[]> = {};

  for (const tweet of tweets) {
    if (!groups[tweet.authorUsername]) {
      groups[tweet.authorUsername] = [];
    }
    groups[tweet.authorUsername].push(tweet);
  }

  // Sort by number of tweets descending
  return Object.fromEntries(
    Object.entries(groups).sort(([, a], [, b]) => b.length - a.length)
  );
}

export function saveReport(content: string, date: string, language: 'en' | 'zh'): void {
  // Save to monthly archive
  const month = date.substring(0, 7);
  const monthDir = join(OUTPUT_DIR, month);
  mkdirSync(monthDir, { recursive: true });

  const filename = `${date}-${language}.md`;
  writeFileSync(join(monthDir, filename), content, 'utf8');

  // Save as latest
  writeFileSync(join(OUTPUT_DIR, 'latest.md'), content, 'utf8');

  console.log(`✅ Saved report: ${filename}`);
}
